### ISSUE TITLE
Multiple accounts

### ISSUE THREAD

**Issue by n8wood** [NicoSantangelo/hangouts-chrome-notifications#1]
Hi, is there any way to select the gmail account you'd like to enable the notifications for?

I noticed it only works for the messages that go to the account that I logged into Chrome with, but I use multiple gmail accounts simultaneously. Thanks.

**Comment by nicosantangelo** [comment]
Hello, there's currently no way to pick the account, but it's a good idea!

I'll give it a go as soon as I have sometime. It probably will be a bit rough UI wise to avoid Google APIs (and to keep things simple)

**Comment by nicosantangelo** [comment]
@n8wood Hi! I tried adding this feature so you could pick and choose your accounts, but there's simply no easy way to accomplish that (and I don't want to add more permissions to the Extension)

So, I added a `"Disable on"` option, where you can add an URL to act as a filter to disable the extension.
In the case of multiple accounts, you can add the full URL (or just the path) containing the account number, like /mail/u/**1**/ to disable it

I know it's not ideal, but I hope it helps,
let me know! this change goes up in version `1.3.0`

**Comment by n8wood** [comment]
@NicoSantangelo just wanted to let you know that this is working great for me now. Thanks!
