### ISSUE TITLE
Try to reliably recognize when the tab is active

### ISSUE THREAD

**Issue by nicosantangelo** [NicoSantangelo/hangouts-chrome-notifications#2]
Maybe give https://github.com/serkanyersen/ifvisible.js a try?

**Comment by siddharth-krishna** [comment]
Is this the issue where I don't get notifications when the hangouts tab is active but Chrome itself is inactive (i.e. another application has focus)? It would be great to have a fix for this! I've currently disabled the option to hide notifications when the tab is active, and the notifications pop up while I'm chatting, which is a bit annoying. Thanks!

**Comment by nicosantangelo** [comment]
That's exactly it. I haven't been able to fix this yet, but to be honest I didn't put enough effort into it.

The main problem I'm trying to fix first is that as it stands now, when I push an update every user has to refresh their Gmail/Hangouts/Inbox tab to keep the extension running. So that's not ideal.

It might be a while but I'll get back to this. As always, PRs are more than welcome!
