### ISSUE TITLE
Please modify "Extension icon popup" onClicked behavior (or add an option) to avoid opening multiple tabs with same "icon click URL"

### ISSUE THREAD

**Issue by lemoran** [NicoSantangelo/hangouts-chrome-notifications#4]
Like the title says, please add an option (may be a checkbox) or modify the default behavior of icon click (background.js line 69) to avoid repeated tabs with the same URL.
It would be good to just switch the tab to the previously opened tab, or to an existent one if the tab URL matches the configured URL.
This behavior may be hardcoded this way or may be depending on a checkbox value that specifies if it's allowed to open multiple tabs with the same URL.

**Comment by nicosantangelo** [comment]
I don't know why I didn't do that from the beginning 😕 

As I explained on #3 my only issue with updating the extension is that I don't have control on the way the Chrome Webstore operates. That said, I think that between this, #3 and some other ideas I have enough of a reason to give it a go.

I can't promise an exact date, so if you really like to have this feature now it should be easy to fork and change it locally. You can upload a zip with your new version to chrome://extensions
